### ISSUE TITLE
The "mildly different ending" doesn't appear to happen?

### ISSUE THREAD

**Issue by Bobjt** [codelazarus14/InhabitantChess#1]
If you read everything you wrote in the readme without the "mildly different ending" happening, the readme instructions don't make sense. When I enable the mod, I confirm its enabled in the in-game mods menu, but visiting the prisoner just goes thru the regular motions without anything different happening. I think it might help you describe more what "mildly different" means? Did I miss something? When do you actually play a board game? In your mildly different ending, does the prisoner sit down in his chair and you can join him at the board? That doesn't happen, unfortunately. And what is this business of a 'shortcut'. You talk a lot about that and I just don't know what it is.

**Comment by codelazarus14** [comment]
Sorry for the confusion, I probably should have made the README less mysterious. The ending is altered with a small sequence where you invite the prisoner to play the game after getting stuck in the simulation together (or at least as long as it takes for the normal supernova-escape timer to elapse, I didn't want to break that in case it was holding something important together).

The ending is normally triggered by setting up the conditions for the "dream" time loop escape ending, which will be intercepted by the mod, instead allowing you to make it to the vault. While testing the mod I quickly got tired of repeating all this setup, so I also created an artifact that sits next to Slate at the start, which teleports you into the vault with the board game set up.  It also skips most of the prisoner's encounter animations/vision torch sequence.

The shortcut used to be locked behind doing the proper time loop escape and vault ending but I've decided to remove the requirement in a new patch, along with some other bug fixes.
